name: Music for the conneseur
favicon: null
layout_spectrum: 0.73082
typography_spectrum: 0.4940742142498493
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0c0c0c'
    - '#ffffff'
    - '#c5c5c5'
    - '#343434'
    - '#7c7c7c'
  brandStrength: 0.053977155359461904
  lightness: 0.33772426610812545
  saturation: 0.22338661132380366
  rhythmicContrast: 0.7965507623739541
purpose: []
